Add `observationType` and `hasQualityMeasurement`
w3c/sdw-sosa-ssn pull request #119
Opened 2023-11-17 05:59 UTC by dr-shorthair

Additional Observation properties mentioned in OMS

2023-11-20 16:49 UTC, KathiSchleidt approved these changes
Looks good!

2023-11-30 14:22 UTC, maximelefrancois86 requested changes
Why is `observationType` in the SOSA namespace ? This object property is not defined in sosa.ttl  and not documented in the specification.

2023-12-01 05:29 UTC, dr-shorthair commented
It is in `sosa:` ns in anticipation of it being added to sosa.ttl. 
See https://github.com/w3c/sdw-sosa-ssn/issues/132

2023-12-03 07:25 UTC, dr-shorthair commented
My suggestion is that we put all the new things in `sosa:` provisionally. 
We can then consider if we need more horizontal modules in due course, which might involve moving some terms into new namespaces. 

(We have a lot of branches and need to do some merging soon else it'll get horribly tangled.)

2023-12-03 09:02 UTC, dr-shorthair commented
Closes #124

2023-12-03 10:44 UTC, sgrellet commented on ssn/integrated/sosa-oms.ttl
> +    schema:domainIncludes osa:Observation ;
sosa:Observation instead of osa:Observation

I guess we'll discuss the range afterwards

2023-12-03 10:45 UTC, sgrellet commented on ssn/integrated/sosa-oms.ttl
> +    schema:domainIncludes osa:Observation ;
the rest looks ok to me

2023-12-03 13:47 UTC, sgrellet approved these changes
fine with me

2023-12-03 21:34 UTC, dr-shorthair commented
> Why is `observationType` in the SOSA namespace ? This object property is not defined in sosa.ttl and not documented in the specification.

For clarity at this stage, I've moved all the terms that are defined in the SOSA-OMS graph into the `sosa-oms:` ns. 
We can consider the final destination in #132. 
@maximelefrancois86 can you approve now so we can merge?

2023-12-04 05:44 UTC, maximelefrancois86 approved these changes

2023-12-05 00:11 UTC, merged