Introduces ProcedureExecution - closes #109
w3c/sdw-sosa-ssn pull request #130
Opened 2023-11-30 16:06 UTC by maximelefrancois86

2023-12-03 21:54 UTC, dr-shorthair commented on ssn/index.html
> +        <section class="specterm ssn" id="SSNProcedureExecution" about="ssn:ProcedureExecution" typeof="owl:Class rdfs:Class">
sosa: ns?

2023-12-03 21:55 UTC, dr-shorthair requested changes
in spec doco change to `sosa:ProcedureExecution`

2023-12-04 08:03 UTC, maximelefrancois86 commented
something is messing up line endings. I'll figure that out.

2023-12-05 01:43 UTC, dr-shorthair commented on ssn/index.html
> +        <section class="specterm ssn" id="SOSAProcedureExecution" about="sosa:ProcedureExecution" typeof="owl:Class rdfs:Class">
Is `specterm ssn` correct here?

2023-12-05 01:45 UTC, dr-shorthair commented on ssn/index.html
> +        <section class="specterm ssn" id="SSNProcedureExecution" about="ssn:ProcedureExecution" typeof="owl:Class rdfs:Class">
Hmm. Still showing ssn:

2023-12-05 13:12 UTC, maximelefrancois86 commented on ssn/index.html
> +        <section class="specterm ssn" id="SOSAProcedureExecution" about="sosa:ProcedureExecution" typeof="owl:Class rdfs:Class">
it's not. well spotted. corrected in commit [c25c0bc](https://github.com/w3c/sdw-sosa-ssn/pull/130/commits/c25c0bc99de362159255bad9c1d3f0ea6efe5184)

2023-12-06 00:10 UTC, dr-shorthair approved these changes

2023-12-06 00:10 UTC, dr-shorthair approved these changes

2023-12-11 03:10 UTC, nicholascar approved these changes

2023-12-11 04:27 UTC, merged