Content model for ProcedureExecution
w3c/sdw-sosa-ssn pull request #173
Opened 2024-01-18 08:16 UTC by dr-shorthair

Closes #164

2024-01-18 08:23 UTC, dr-shorthair commented
Should `hadInput` be added - see #105 ?

2024-01-18 20:26 UTC, rob-metalinkage reviewed
A super  class has value for schema implementation - so agree.  Consider using Activity from the PROV alignment. 

Evidence of implementation can be supported by a common schema in the OGC PAI-SOSA implementation.

2024-01-18 20:28 UTC, ldesousa commented
After the explanation during today's conference call the role of this class became clear. However, I am concerned the name may generate some confusion. It is not as concise as the other main concepts and contains the name of an existing class (`Procedure`). Names like `Action` (OMD software) or `Activity` (from Prov ontology) to my mind would be more effective.

2024-01-18 20:29 UTC, sgrellet commented
agreed. 

during Jan 18th webconf the issue of name conflict between `ProcedureExecution `and `sosa:Procedure` was raised. 

Not the interest of this new class (which makes a lot of sense as it gives reality to an implictly common super class), just its naming. To avoid misunderstanding by users.

A suggestion was to name it Activity. And it would actually be interesting to consider link with prov:Activity (subtyping?)

2024-01-19 06:10 UTC, dr-shorthair commented
@maximelefrancois86 it seems that the name `ProcedureExecution` is causing some confusion. 
Would renaming to `sosa:Activity` (parallel to `prov:Activity`) cause any problems?

2024-01-19 08:59 UTC, maximelefrancois86 commented
I'd be ok with a simpler name, but note many properties that would be attached to that class would be weird if attached to `Activity`:
- `madeBy`
- `hasFeatureOfInterest`
- `hasUltimateFeatureOfInterest`
- `hasResultTime`

Users may wonder why such a general concept like `Activity` needs to be made by a sensor/actuator, be about a feature of interest, and have exactly one result...

I thought the name `ProcedureExecution` would help to make clear the distinction with `Procedure`.

DUL and PROV-O alignments are both important and structuring.

PROV-O offers Activity as you pointed out

DUL offers:
> Event: Any physical, social, or mental process, event, or state.
> Action -> An Event with at least one Agent that isParticipantIn it, and that executes a Task that typically isDefinedIn a Plan, Workflow, Project, etc. ------> this perfectly aligns to our idea of what a procedure execution is 
> Process -> This is a placeholder for events that are considered in their evolution, or anyway not strictly dependent on agents, tasks, and plans.

2024-01-19 10:26 UTC, hylkevds commented
One advantage of the name ProcedureExecution is that it is quite clearly the Execution of a Procedure, and not some other, non-Procedure-related Activity.
How about just `Execution`? Since that name implies that there is something else that is being executed (a program or procedure).

2024-01-19 10:59 UTC, maximelefrancois86 commented
I'd be happy with `Execution`

2024-01-21 05:44 UTC, dr-shorthair commented
I just added `hasInputValue` and `hasOutputValue` for use on `Executions`. 
But I have a feeling more documentation and justification or patterns is required. 
Can @hylkevds or @alexrobin or @maximelefrancois86 or @sgrellet step in here please? 

FWIW I'm somewhat uncertain of the `hasOutputValue` semantics and how it relates to `hasResult`.

2024-01-21 05:47 UTC, dr-shorthair commented
As usual, the browser view for this branch can be seen at https://raw.githack.com/w3c/sdw-sosa-ssn/ProcedureExecution-spec/ssn/index.html

2024-01-22 08:52 UTC, hylkevds commented
`hasInputValue` and `hasOutputValue` will need two properties: 
- One that points to what the `hasInput` / `hasOutput` of the Procedure points to. How about `forInput` / `forOputput`?
- One that points to the actual value. `hasValue`?

The text is a bit confused at the moment. How about:
has Input Value - Assigns a value (`hasValue`) to an input (`forInput`) defined by the Procedure that is implemented by an Execution (Actuation, Observation, Sampling).

2024-01-23 05:17 UTC, dr-shorthair commented
Thank you for the suggested improvement to the wording. 

I'm reluctant to propose a detailed content model for the object of `hasInputValue` and `hasOutputValue` without implementation experience. These terms will probably need to be tagged `non-normative` anyway. If you do want to push this further, then can you do it in concrete form through a PR?

2024-01-25 05:49 UTC, dr-shorthair commented
closes #105

2024-01-28 05:18 UTC, dr-shorthair commented
@hylkevds to push this further can you make a PR?

2024-01-29 23:18 UTC, dr-shorthair commented
This PR must be merged prior to the major modularization work suggested in https://github.com/w3c/sdw-sosa-ssn/issues/183#issuecomment-1913860023 

We can revisit the hasInputValue issue later if required. (@hylkevds you can create a new issue for that)

2024-01-30 07:27 UTC, hylkevds approved these changes

2024-01-30 10:25 UTC, alexrobin commented
I personally liked the name `ProcedureExecution` better.
I find the `Execution` term too vague given that we are talking about a very specific type of execution.
I don't think having a longer name really matters since this class is not meant to be used directly.

I agree with @dr-shorthair that we should revisit the definition of input/output at a later stage (separate PR) since I feel it can get complicated...

2024-01-30 11:29 UTC, maximelefrancois86 approved these changes

2024-01-30 11:38 UTC, maximelefrancois86 commented
> `hasInputValue` and `hasOutputValue` will need two properties:
> 
> * One that points to what the `hasInput` / `hasOutput` of the Procedure points to. How about `forInput` / `forOputput`?
> * One that points to the actual value. `hasValue`?
> 
> The text is a bit confused at the moment. How about: has Input Value - Assigns a value (`hasValue`) to an input (`forInput`) defined by the Procedure that is implemented by an Execution (Actuation, Observation, Sampling).

We would solve this problem differently in SAREF ([ETSI TS 103264 V3.2.1](https://www.etsi.org/deliver/etsi_ts/103200_103299/103264/03.02.01_60/ts_103264v030201p.pdf)): applications would define different sub-properties of hasInput to distinguish the different inputs, and these sub-properties would apply to commands and to executions of that command. In the case of controlling an oven, inputs could be: `ex:hasPhase1TemperatureIncreaseRate`, `ex:hasPhase1Duration`, `ex:hasPhase2ConstantTemperature`, `ex:hasPhase2Duration` ...

2024-01-30 15:44 UTC, ldesousa requested changes, later dismissed

2024-01-30 15:44 UTC, ldesousa commented on ssn/index.html
>            <em property="rdfs:label">Procedure Execution</em> -
Shouldn't it be just "Execution"?

2024-01-30 15:44 UTC, ldesousa commented on ssn/index.html
> +        <section class="informative specterm" id="SOSAExecution" about="sosa:Execution" typeof="owl:Class rdfs:Class">
This class (and the subsequent properties) are a bit lost in this section (`Procedure`). Since `Observation`, `Actuation` and `Sampling` are sub-classes, `Execution` could justify its own section in the HTML. As of now it would be a fully non-normative section. Could also be expanded with text justifying its introduction.

Thoughts?

2024-01-30 15:44 UTC, ldesousa commented on ssn/integrated/sosa-oms.ttl
> +    schema:domainIncludes sosa:ProcedureExecution ;
Should be `sosa:Execution`.

2024-01-30 15:44 UTC, ldesousa commented on ssn/integrated/ssn.ttl
>    rdfs:label "Procedure Execution"@en ;
Or just "Execution"?

2024-01-30 15:44 UTC, ldesousa commented on ssn/integrated/sosa.ttl
>    rdfs:label "Procedure Execution"@en ;
"Execution" instead?

2024-01-30 15:44 UTC, ldesousa commented on ssn/index.html
ReSpec is flagging one error and four warning when this file is rendered. Anything to worry about?

2024-01-30 22:37 UTC, dr-shorthair commented on ssn/index.html
>            <em property="rdfs:label">Procedure Execution</em> -
The Label does not have to match the class name, else there would be no need for a label. 
However, I've adjusted it to 'Execution of Procedure'

2024-01-30 22:38 UTC, dr-shorthair commented on ssn/index.html
> +        <section class="informative specterm" id="SOSAExecution" about="sosa:Execution" typeof="owl:Class rdfs:Class">
I agree that the position of sosa:Execution in the document could be changed. 
Let's look at this in the context of the larger reorganisation that is being considered.

2024-01-30 22:42 UTC, dr-shorthair commented on ssn/integrated/ssn.ttl
>    rdfs:label "Procedure Execution"@en ;
See above.

2024-01-30 22:42 UTC, dr-shorthair commented on ssn/integrated/sosa.ttl
>    rdfs:label "Procedure Execution"@en ;
Label not needed in this file.

2024-01-30 22:42 UTC, dr-shorthair commented on ssn/index.html
I've squashed the error. Will look at the warnings in another thread.

2024-01-30 22:43 UTC, merged