182 conformance and normative terms
w3c/sdw-sosa-ssn pull request #198
Opened 2024-03-02 04:21 UTC by dr-shorthair

Closes #182

2024-03-04 05:59 UTC, dr-shorthair commented
@sgrellet @hylkevds @ldesousa 
Can you review this please? It is a minor addition that will get rid of one of the respec warnings. 

Would also be interested in your additions to the actual content of the Conformance statement - see https://github.com/w3c/sdw-sosa-ssn/pull/198/files#diff-380de27307896ad97825cbc8b0794c863bb203aa37c80d2351b27b9982e3b204

2024-03-04 06:45 UTC, ldesousa commented
> @sgrellet @hylkevds @ldesousa Can you review this please? It is a minor addition that will get rid of one of the respec warnings.
> 
> Would also be interested in your additions to the actual content of the Conformance statement - see https://github.com/w3c/sdw-sosa-ssn/pull/198/files#diff-380de27307896ad97825cbc8b0794c863bb203aa37c80d2351b27b9982e3b204

My agenda is too heavy the next two days. I will be having a look on the 6th of March. That's about 32 hours before the next meeting.

2024-03-04 07:36 UTC, hylkevds approved these changes
LGTM.

2024-03-06 08:51 UTC, ldesousa requested changes
Small things for further thought. Fine for me if you merge outright.

In parallel I pushed some additions to the conformance articles in Conformance.html, please cross-review those.

2024-03-06 08:51 UTC, ldesousa commented on ssn/index.html
> +      SOSA MAY be used <i>as-is</i> by an audience who wish to use terminology consistent with the SSN Ontology, thus
This makes "MAY" look like an acronym. I suggest using bold, italics, underlined or a combination of those to highlight these terms.

2024-03-06 08:51 UTC, ldesousa commented on ssn/index.html
> +        <li>With CDT, the value of <a href="#SOSAhasSimpleResult"><code>sosa:hasSimpleResult</code></a> can be
Why is "MAY" highlighted, and "can" not?

2024-03-07 00:03 UTC, dr-shorthair commented on ssn/index.html
> +        <li>With CDT, the value of <a href="#SOSAhasSimpleResult"><code>sosa:hasSimpleResult</code></a> can be
MAY is a normative term. 
'can' is not (according to the IETF standard). 

But this whole section is to be replaced by work that I'm doing on the Patterns section in another branch.

2024-03-07 00:06 UTC, dr-shorthair commented on ssn/index.html
> +      SOSA MAY be used <i>as-is</i> by an audience who wish to use terminology consistent with the SSN Ontology, thus
The Conformance rules require that the normative terms be cast into UPPER CASE where they are being used normatively.

2024-03-07 00:09 UTC, dr-shorthair commented
Thanks @ldesousa  - your mods are good. 
Can you release this now?

2024-03-07 09:43 UTC, ldesousa approved these changes

2024-03-07 10:09 UTC, merged