SAREF-SOSA alignment and first approx doc, closes #125
w3c/sdw-sosa-ssn pull request #206
Opened 2024-03-14 10:48 UTC by maximelefrancois86

Alignment to SAREF and draft documentation

* alignment in `ssn/mappings/sosa-saref-mapping.ttl`
* updated references to SAREF and SAREF patterns in `config.js`
* drafted documentation in `ssn/frag/SAREF-alignment.html`

to previsualize: https://raw.githack.com/w3c/sdw-sosa-ssn/lefrancois-saref-alignment/ssn/index.html

2024-03-14 12:57 UTC, maximelefrancois86 commented
@rgcmme Maybe you want to check this out ?

2024-03-19 00:27 UTC, dr-shorthair commented on ssn/config.js
> +    "OMS": {
OMS is in SpecRef so does not need an entry in the local bibliography
https://www.specref.org/?q=oms

2024-03-19 00:28 UTC, dr-shorthair approved these changes

2024-03-19 00:32 UTC, dr-shorthair commented on ssn/config.js
> +    "OMS": {
Fixed

2024-03-19 02:22 UTC, dr-shorthair commented
Closes #125

2024-03-20 15:42 UTC, rgcmme commented
SOSA has no formal axiomatization, since all of it has been moved to SSN. Therefore, since the mapping is only between SOSA and SAREF, the relationships should be in the other direction.

That is, by making `sosa:FeatureOfInterest` (no axioms) subclass of `saref:FeatureOfInterest` (with axioms), `sosa:FeatureOfInterest` is inheriting many axioms that may not apply.

If the mapping would be between SAREF and SSN, every class should be analysed in detail. SSN has some cardinality restrictions that would make such mapping difficult (e.g., is it needed for every `sosa:Execution` to always have both a start time and a result time?).

Also, the mappings between inputs and outputs are strange; because of the "`/sosa/saref`" URIs, and there is a typo in the `sosa:hasOutputValue` one. In SAREF inputs and outputs are only applied to commands, but in SOSA/SSN to procedures.

2024-03-20 15:50 UTC, maximelefrancois86 commented
I based the alignment on the literal definitions, mostly.
The goal here would only be that nothing breaks when importing SSN + SAREF + this alignment, 

Regarding the mappings between inputs and outputs, they are strange indeed. I don't think either is more specific than the other, so I created a common super-property. Note that in SAREF inputs and outputs apply not only to commands:

saref:hasInput has Domain ( saref:Command or saref:CommandOfInterest or saref:Operation or saref:ProcedureExecution )
saref:hasOutput has Domain ( saref:Command or saref:CommandOfInterest or saref:Operation )

2024-03-20 16:10 UTC, rgcmme commented
If the mappings are based in the textual definitions, from the "textual" perspective they compile. 😄 

However, if they are formally encoded (using for example `rdfs:subClassOf`), then there will be formal entailments.

In the case of SOSA, with no axiomatization, nothing will break (even if the mappings are not correct). 

If the mapping would be between SSN and SAREF, this may not be the case, since both ontologies impose their own restrictions that may not be compatible (or produce the intended result). But I haven't made that detailed analysis. And it also depends on the definition of "break", but it may happen that one SSN individual is not a valid SAREF individual (e.g., because of cardinality constraints).

2024-03-20 23:11 UTC, dr-shorthair commented
> SSN has some cardinality restrictions that would make such mapping difficult

I'm not fully confident in the cardinality restrictions. 
Most of them are my clumsy way of adding some 'expectations'. 
But cardinalities are probably better handled in the application, or using SHACL (which is planned by OGC in the next phase). 

Would it be best to remove all cardinality constraints from the ssn graphs?

2024-03-21 07:41 UTC, rgcmme commented
I am in favour of the cardinality restrictions and any other axiom that further specifies the meaning and restrictions of the concepts.

Ontologies are a good way of sharing those restrictions in a machine-procesable way; leaving applications the role of handling those restrictions will cause heterogeneity and hinder interoperability. 

And using SHACL will require implementors to know/learn both OWL and SHACL and having to search for the restrictions in two places.

In any case, every option is valid in principle. My take would be, for those restrictions that are clear, to have them in OWL and in the future in SHACL.

I would try to avoid having restrictions in SHACL that do not appear in OWL (for those restrictions that can be defined in both places).

2024-04-10 11:53 UTC, rob-metalinkage requested changes
convert circular subproperty alignments for *:hasInput to a skos:closeMatch

2024-04-24 00:50 UTC, dr-shorthair commented
On cardinalities:

> e.g., is it needed for every sosa:Execution to always have both a start time and a result time?

The way I understand it is that every Execution does necessarily have a start and end (result) time in the world. 
However, these may not be known or expressed in any particular representation ... but that is handled by the OWA. 

Does putting a minCardinality=1 in the OWL mean that a dataset without that property is 'wrong'? 
I don't think so, OWL processing does not allow for that judgement, it can only generate entailments. 
The entailment in such a case is that there is an unknown value ...

2024-04-24 07:22 UTC, rgcmme commented
Of course, OWL and the OWA are able of handling this correctly.

However, sooner or later someone will define closed world constraints (SHACL is mentioned in this same thread) and the restriction "every execution has a start date and there is no problem if you don't find it" becomes "every execution has a start date and your data is incorrect because it does not". 

The fact that every execution always has a start time can be documented in the rdfs:comment of sosa:Execution (with no strong semantics associated to it) and leave to users the decision of whether they want that to be a strong constraint (by extending SSN with further restrictions) in their applications.

At least in this case I think that it is a restriction that will not hold for many applications.

2024-04-24 08:52 UTC, dr-shorthair commented
> sooner or later someone will define closed world constraints (SHACL) [that are too strict or onerous] 

We recognise that risk, and propose to address it by providing shared SHACL constraints that manage things like cardinality. This is on the agenda for related work to be done inside OGC - see https://github.com/w3c/sdw-sosa-ssn/issues/142 and https://github.com/opengeospatial/ogcapi-sosa/issues/4 

There is a placeholder space for SHACL resources here https://github.com/w3c/sdw-sosa-ssn/tree/gh-pages/ssn/rdf/shapes

2024-05-07 11:01 UTC, dr-shorthair commented
@rob-metalinkage can you check if your concern has been addressed?

2024-05-22 12:16 UTC, rob-metalinkage approved these changes
I think so - adding a superproperty in the saref alignment avoids circular ref.

2024-05-23 07:07 UTC, merged