259 simplify diagrams
w3c/sdw-sosa-ssn pull request #260
Opened 2024-10-30 05:02 UTC by dr-shorthair

Simplify diagrams by omitting all properties except the key ones that are essential to understanding and using the SSN classes. 
Feedback from CODATA workshop was that showing ancillary properties such as 'hasInputValue' distracted from the main message. 

Note that diagrams are only informative and their goal is to provide a quick introduction. 
They are already selective in terms of what is shown. This change just focuses more. 

Preview:  https://raw.githack.com/w3c/sdw-sosa-ssn/259-simplify-diagrams/ssn/index.html 

Closes #259

2024-10-31 09:04 UTC, ldesousa requested changes, later dismissed

2024-10-31 09:04 UTC, ldesousa commented on ssn/images/Observation.png
The *Information* class might be confusing. Even I am not sure what it means. I suggest using `owl:Thing` (or narrower) instead.

2024-11-05 00:53 UTC, dr-shorthair commented on ssn/images/Observation.png
`owl:Thing` is too broad. 
The result of an observation is information. 

However, I admit that the class name may be confusing even if it is explained in the figure caption. 
So I deleted the name and just left it blank, and tweaked the caption.

2024-11-27 02:53 UTC, oldskeptic approved these changes

2024-11-27 03:10 UTC, nicholascar approved these changes

2024-11-27 06:22 UTC, merged

2024-11-27 07:57 UTC, sgrellet reviewed
LGTM